"""Regenerate the production sample tables using AE's zero-mean Vogel pattern."""
from pathlib import Path
import math

def generate():
    text = '// Generated by tests/generate_samples.py; u, v, normalized radius, squared radius.\n'
    for count in (64, 128, 256, 512):
        points = []
        for i in range(count):
            r = math.sqrt((i + .5) / count)
            angle = i * 2.39996322972865332
            points.append((r * math.cos(angle), r * math.sin(angle), r))
        mx = sum(p[0] for p in points) / count
        my = sum(p[1] for p in points) / count
        rows = ['    float4(' + ', '.join(f'{v:.9g}' for v in (x-mx, y-my, r, r*r)) + ')' for x,y,r in points]
        text += f'static const float4 samples{count}[{count}] = {{\n' + ',\n'.join(rows) + '\n};\n'
    return text

if __name__ == '__main__':
    path = Path(__file__).resolve().parents[1] / 'ymm/Shaders/Samples.hlsli'
    path.write_text(generate(), encoding='utf-8')
